CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin',
  pin_hash TEXT NOT NULL,
  color TEXT DEFAULT '#ba935a',
  avatar_url TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  token_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tables (
  id TEXT PRIMARY KEY,
  table_number INTEGER NOT NULL UNIQUE,
  name TEXT NOT NULL DEFAULT '',
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS system_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  user_name TEXT,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  details TEXT,
  ip_address TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS menu_categories (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  italian_title TEXT NOT NULL,
  description TEXT,
  display_order INTEGER DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS menu_items (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  italian_name TEXT,
  description TEXT,
  price REAL NOT NULL,
  category TEXT NOT NULL,
  image TEXT,
  calories INTEGER,
  preparation_time TEXT,
  tags TEXT,
  badge TEXT,
  pronunciation TEXT,
  active INTEGER NOT NULL DEFAULT 1,
  display_order INTEGER DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_categories_order ON menu_categories(display_order);
CREATE INDEX IF NOT EXISTS idx_categories_active ON menu_categories(active);
CREATE INDEX IF NOT EXISTS idx_menu_category ON menu_items(category);
CREATE INDEX IF NOT EXISTS idx_menu_active ON menu_items(active);



INSERT OR REPLACE INTO system_settings (key, value) VALUES ('guestWifiSsid', 'CasaItalia_Guest');
INSERT OR REPLACE INTO system_settings (key, value) VALUES ('guestWifiPassword', 'casaitaliaportghalib');
INSERT OR REPLACE INTO system_settings (key, value) VALUES ('restaurantPhone', '+20 150 830 0656');
INSERT OR REPLACE INTO system_settings (key, value) VALUES ('restaurantEmail', 'info@casaitaliarestaurants.com');
INSERT OR REPLACE INTO system_settings (key, value) VALUES ('openingHours', '12:00 PM - 11:30 PM');

INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_1', 1, 'Table 1', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_2', 2, 'Table 2', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_3', 3, 'Table 3', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_4', 4, 'Table 4', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_5', 5, 'Table 5', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_6', 6, 'Table 6', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_7', 7, 'Table 7', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_8', 8, 'Table 8', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_9', 9, 'Table 9', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_10', 10, 'Table 10', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_11', 11, 'Table 11', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_12', 12, 'Table 12', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_13', 13, 'Table 13', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_14', 14, 'Table 14', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_15', 15, 'Table 15', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_16', 16, 'Table 16', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_17', 17, 'Table 17', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_18', 18, 'Table 18', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_19', 19, 'Table 19', 1, '2026-09-19T19:35:02.714Z');
INSERT OR IGNORE INTO tables (id, table_number, name, active, created_at) VALUES ('table_20', 20, 'Table 20', 1, '2026-09-19T19:35:02.714Z');

INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('antipasti', 'Antipasti', 'Antipasti della Casa', 'Starters & Appetizers', 1, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('primi', 'Primi Piatti', 'Primi Piatti Classici', 'Traditional Italian Pasta & Risotto', 2, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('pasta_fresca', 'Pasta Fresca', 'Pasta Fresca', 'Fresh Pasta & Lasagna', 3, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('secondi_carne', 'Secondi Carne', 'Secondi Piatti di Carne', 'Gourmet Meat Specialties & Steaks', 4, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('secondi_pesce', 'Secondi Pesce', 'Secondi Piatti di Pesce', 'Fresh Mediterranean Seafood & Fish', 5, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('contorni', 'Contorni', 'Contorni e Side Dishes', 'Fresh Sides & Vegetables', 6, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('burger', 'Burgers', 'Burger Gourmet', 'Handcrafted 200g Beef & Vegan Burgers', 7, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('insalate', 'Insalate', 'Insalate Fresche', 'Fresh Seasonal Salads', 8, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('pizze_rosse', 'Pizze Rosse', 'Pizze Tradizionali con Pomodoro', 'Wood-Fired Red Base Pizzas', 9, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('pizze_bianche', 'Pizze Bianche', 'Pizze Bianche Speciali', 'Gourmet White Base Pizzas', 10, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('dolci', 'Dolci', 'Dolci e Dessert', 'Artisanal Desserts & Tiramisù', 11, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('caffetteria', 'Caffetteria', 'Caffetteria Italiana', 'Espresso, Cappuccino & Hot Drinks', 12, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('bibite', 'Bibite', 'Bibite & Refreshments', 'Cold Beverages, Waters & Juices', 13, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('vini', 'Vini', 'Carta dei Vini', 'Curated Italian Wines', 14, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('birre', 'Birre', 'Selezione di Birre', 'Draft & Bottled Beers', 15, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('cocktails', 'Cocktails', 'Cocktails & Aperitivi', 'Signature Cocktails & Mocktails', 16, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_categories (id, name, italian_title, description, display_order, active, created_at, updated_at) VALUES ('colazione', 'Colazione', 'Colazione Italiana', 'Breakfast Croissants & Dishes', 17, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');

INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tartare-di-tonno-all-arancia-1', 'Tuna Tartare with Orange', 'TARTARE DI TONNO ALL''ARANCIA', 'Tuna tartare with orange cream', 15, 'antipasti', 'https://cdn.casaitaliarestaurants.com/menu/Appetizers/TARTARE DI TONNO ALL ARANCIA.webp', NULL, NULL, '[]', NULL, NULL, 1, 1, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('polpo-alla-piastra-su-vellutata-di-patate-olive-e-pomodorini-2', 'Grilled Octopus on Potato Cream', 'POLPO ALLA PIASTRA SU VELLUTATA DI PATATE, OLIVE E POMODORINI', 'Grilled octopus on a cream of potatoes, olives and cherry tomatoes', 17, 'antipasti', 'https://cdn.casaitaliarestaurants.com/menu/Appetizers/POLPO ALLA PIASTRA.webp', NULL, NULL, '[]', NULL, NULL, 1, 2, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tartare-di-salmone-al-mango-3', 'Salmon Tartare with Mango', 'TARTARE DI SALMONE AL MANGO', 'Salmon tartare with mango cream', 15, 'antipasti', 'https://cdn.casaitaliarestaurants.com/menu/Appetizers/TARTARE DI SALMONE AL MANGO.webp', NULL, NULL, '[]', NULL, NULL, 1, 3, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tris-di-crostini-con-pat-di-fegatini-pomodoro-e-basilico-pecorino-e-guanciale-4', 'Tuscan Crostini Trio', 'TRIS DI CROSTINI CON PATÉ DI FEGATINI, POMODORO E BASILICO, PECORINO E GUANCIALE', 'Trio of crostini with liver pâté, fresh tomato and basil, pecorino cheese and guanciale', 15, 'antipasti', 'https://cdn.casaitaliarestaurants.com/menu/Appetizers/TRIS DI CROSTINI.webp', NULL, NULL, '[]', NULL, NULL, 1, 4, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('gran-tagliere-casa-italia-di-salumi-e-formaggi-5', 'Casa Italia Grand Charcuterie Board', 'GRAN TAGLIERE ''CASA ITALIA'' DI SALUMI E FORMAGGI', 'Platter ''Casa Italia'' with cold cuts and cheeses', 29, 'antipasti', 'https://cdn.casaitaliarestaurants.com/menu/Appetizers/GRAN TAGLIERE CASA ITALIA.webp', NULL, NULL, '[]', NULL, NULL, 1, 5, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('parmigiana-di-melanzane-6', 'Eggplant Parmigiana', 'PARMIGIANA DI MELANZANE', 'Eggplant parmigiana', 11, 'antipasti', 'https://cdn.casaitaliarestaurants.com/menu/Appetizers/PARMIGIANA DI MELAZANE.webp', NULL, NULL, '[]', NULL, NULL, 1, 6, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('carpaccio-di-manzo-servito-con-rucola-noci-scaglie-di-parmigiano-capperi-e-crema-di-parmigiano-7', 'Gourmet Beef Carpaccio', 'CARPACCIO DI MANZO SERVITO CON RUCOLA, NOCI, SCAGLIE DI PARMIGIANO, CAPPERI E CREMA DI PARMIGIANO', 'Beef carpaccio served with rocket, nuts, parmesan scales, capers and parmesan cream', 19, 'antipasti', 'https://cdn.casaitaliarestaurants.com/menu/Appetizers/CARPACCIO DI MANZO.webp', NULL, NULL, '[]', NULL, NULL, 1, 7, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('vitello-tonnato-8', 'Classic Vitello Tonnato', 'VITELLO TONNATO', 'Veal with tuna sauce', 17, 'antipasti', 'https://cdn.casaitaliarestaurants.com/menu/Appetizers/VITELLO TONNATO.webp', NULL, NULL, '[]', NULL, NULL, 1, 8, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tartare-di-manzo-servita-con-tuorlo-d-uovo-e-crema-di-parmigiano-9', 'Beef Tartare with Egg Yolk & Parmesan', 'TARTARE DI MANZO SERVITA CON TUORLO D''UOVO E CREMA DI PARMIGIANO', 'Beef tartare served with raw egg yolk and parmesan cream', 17, 'antipasti', 'https://cdn.casaitaliarestaurants.com/menu/Appetizers/TARTARE DI MANZO.webp', NULL, NULL, '[]', NULL, NULL, 1, 9, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('penne-pomodoro-basilico-e-stracciatella-10', 'Penne Tomato & Stracciatella', 'PENNE POMODORO, BASILICO E STRACCIATELLA', 'Penne with tomato, basil and stracciatella', 14, 'primi', 'https://cdn.casaitaliarestaurants.com/menu/pasta/PENNE POMODORO.webp', NULL, NULL, '[]', NULL, NULL, 1, 10, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('rigatoni-alla-bolognese-11', 'Rigatoni Bolognese', 'RIGATONI ALLA BOLOGNESE', 'Rigatoni with bolognese ragù', 16, 'primi', 'https://cdn.casaitaliarestaurants.com/menu/pasta/RIGATONI ALLA BOLOGNESE.webp', NULL, NULL, '[]', NULL, NULL, 1, 11, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('spaghetti-alla-carbonara-12', 'Authentic Spaghetti Carbonara', 'SPAGHETTI ALLA CARBONARA', 'Spaghetti with eggs sauce and guanciale', 18, 'primi', 'https://cdn.casaitaliarestaurants.com/menu/pasta/SPAGHETTI ALLA CARBONARA.webp', NULL, NULL, '[]', NULL, NULL, 1, 12, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('penne-al-salmone-13', 'Penne with Salmon', 'PENNE AL SALMONE', 'Penne with smoked salmon sauce', 20, 'primi', 'https://cdn.casaitaliarestaurants.com/menu/pasta/PENNE AL SALMONE.webp', NULL, NULL, '[]', NULL, NULL, 1, 13, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('spaghetti-ai-frutti-di-mare-14', 'Seafood Spaghetti', 'SPAGHETTI AI FRUTTI DI MARE', 'Seafood spaghetti', 20, 'primi', 'https://cdn.casaitaliarestaurants.com/menu/pasta/SPAGHETTI AL FRUTTI DI MARE.webp', NULL, NULL, '[]', NULL, NULL, 1, 14, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('risotto-ai-crostacei-e-burrata-15', 'Shellfish & Burrata Risotto', 'RISOTTO AI CROSTACEI E BURRATA', 'Risotto with shellfish and burrata', 20, 'primi', 'https://cdn.casaitaliarestaurants.com/menu/pasta/RISOTTO AL CROSTACEI E BURRATA.webp', NULL, NULL, '[]', NULL, NULL, 1, 15, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('risotto-al-tartufo-16', 'Truffle Risotto', 'RISOTTO AL TARTUFO', 'Truffle risotto', 20, 'primi', 'https://cdn.casaitaliarestaurants.com/menu/pasta/RISOTTO AL TARUFO.webp', NULL, NULL, '[]', NULL, NULL, 1, 16, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tortellini-panna-e-prosciutto-17', 'Tortellini with Cream & Prosciutto', 'TORTELLINI PANNA E PROSCIUTTO', 'Tortellini with cream and cooked ham', 20, 'pasta_fresca', '', NULL, NULL, '[]', NULL, NULL, 1, 17, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('lasagna-al-rag-18', 'Beef Lasagna', 'LASAGNA AL RAGÙ', 'Lasagna with meat sauce', 28, 'pasta_fresca', 'https://cdn.casaitaliarestaurants.com/menu/fresh pasta/LASAGNA AL RAGU.webp', NULL, NULL, '[]', NULL, NULL, 1, 18, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('gnocchi-verdi-agli-spinaci-19', 'Spinach Gnocchi', 'GNOCCHI VERDI AGLI SPINACI', 'Green gnocchi with spinach sauce', 15, 'pasta_fresca', 'https://cdn.casaitaliarestaurants.com/menu/fresh pasta/GNOCCHI VERDI AGLI SPINACI.webp', NULL, NULL, '[]', NULL, NULL, 1, 19, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('gnocchi-al-rag-20', 'Gnocchi with Meat Ragù', 'GNOCCHI AL RAGÙ', 'Gnocchi with meat sauce', 16, 'pasta_fresca', 'https://cdn.casaitaliarestaurants.com/menu/fresh pasta/GNOCCHI AL RAGU.webp', NULL, NULL, '[]', NULL, NULL, 1, 20, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('ravioli-ripieni-ai-4-formaggi-serviti-con-salsa-al-gorgonzola-21', 'Four Cheese Ravioli with Gorgonzola Sauce', 'RAVIOLI RIPIENI AI 4 FORMAGGI SERVITI CON SALSA AL GORGONZOLA', 'Ravioli stuffed with four cheeses served with blue cheese sauce', 16, 'pasta_fresca', 'https://cdn.casaitaliarestaurants.com/menu/fresh pasta/RAVIOLI RIPIENI AL 4 FORMAGGI.webp', NULL, NULL, '[]', NULL, NULL, 1, 21, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('ravioli-ripieni-al-salmone-serviti-con-salsa-al-salmone-22', 'Salmon Ravioli with Salmon Sauce', 'RAVIOLI RIPIENI AL SALMONE SERVITI CON SALSA AL SALMONE', 'Ravioli stuffed with salmon served with salmon sauce', 18, 'pasta_fresca', 'https://cdn.casaitaliarestaurants.com/menu/fresh pasta/RAVIOLI  RIPIENI AL SALMONE.webp', NULL, NULL, '[]', NULL, NULL, 1, 22, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('ravioli-ripieni-al-tartufo-serviti-con-salsa-al-tartufo-23', 'Truffle Ravioli with Truffle Sauce', 'RAVIOLI RIPIENI AL TARTUFO SERVITI CON SALSA AL TARTUFO', 'Ravioli stuffed with truffle served with truffle sauce', 17, 'pasta_fresca', 'https://cdn.casaitaliarestaurants.com/menu/fresh pasta/RAVIOLI RIPIENI AL TARTUFO.webp', NULL, NULL, '[]', NULL, NULL, 1, 23, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('ravioli-ripieni-ricotta-e-spinaci-serviti-con-salsa-agli-spinaci-24', 'Ricotta & Spinach Ravioli', 'RAVIOLI RIPIENI RICOTTA E SPINACI SERVITI CON SALSA AGLI SPINACI', 'Ravioli stuffed with ricotta and spinach served with spinach sauce', 15, 'pasta_fresca', 'https://cdn.casaitaliarestaurants.com/menu/fresh pasta/RAVIOLI RIPIENI RICOTTA E SPINACI.webp', NULL, NULL, '[]', NULL, NULL, 1, 24, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('filetto-di-manzo-al-pepe-o-ai-funghi-con-patate-al-forno-e-verdure-saltate-25', 'Beef Tenderloin Steak', 'FILETTO DI MANZO AL PEPE O AI FUNGHI CON PATATE AL FORNO E VERDURE SALTATE', 'Beef fillet with pepper sauce or mushrooms sauce served with baked potatoes and sautèed vegetables', 24, 'secondi_carne', 'https://cdn.casaitaliarestaurants.com/menu/Main dishes/FILETTO DI MANZO.webp', NULL, NULL, '[]', NULL, NULL, 1, 25, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('bistecca-di-manzo-alla-piastra-con-verdure-e-patatine-fritte-26', 'Grilled Beef Steak with Vegetables & Fries', 'BISTECCA DI MANZO ALLA PIASTRA CON VERDURE E PATATINE FRITTE', 'Grilled beef steak with vegetables and french fries', 26, 'secondi_carne', '', NULL, NULL, '[]', NULL, NULL, 1, 26, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('filetto-di-cammello-al-pepe-con-patate-al-forno-e-verdure-saltate-27', 'Camel Fillet with Pepper Sauce', 'FILETTO DI CAMMELLO AL PEPE CON PATATE AL FORNO E VERDURE SALTATE', 'Camel fillet with pepper sauce served with baked potatoes and sautèed vegetables', 26, 'secondi_carne', '', NULL, NULL, '[]', NULL, NULL, 1, 27, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('pollo-al-limone-con-pur-28', 'Lemon Chicken with Mashed Potatoes', 'POLLO AL LIMONE CON PURÈ', 'Lemon chicken with mashed potatoes', 18, 'secondi_carne', 'https://cdn.casaitaliarestaurants.com/menu/Main dishes/POLLO AL LIMONE.webp', NULL, NULL, '[]', NULL, NULL, 1, 28, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('pollo-affumicato-con-salsa-di-peperoni-affumicati-servito-con-pur-29', 'Smoked Chicken with Roasted Pepper Sauce', 'POLLO AFFUMICATO CON SALSA DI PEPERONI AFFUMICATI SERVITO CON PURÈ', 'Smoked chicken with smoked peppers sauce served with mashed potatoes', 18, 'secondi_carne', 'https://cdn.casaitaliarestaurants.com/menu/Main dishes/POLLO AFFUMICATO CON SALSA DI PEPERONI.webp', NULL, NULL, '[]', NULL, NULL, 1, 29, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cotoletta-di-pollo-servita-con-insalata-verde-30', 'Chicken Cutlet with Green Salad', 'COTOLETTA DI POLLO SERVITA CON INSALATA VERDE', 'Chicken panè served with green salad', 20, 'secondi_carne', 'https://cdn.casaitaliarestaurants.com/menu/Main dishes/COTOLETTA DI POLLO.webp', NULL, NULL, '[]', NULL, NULL, 1, 30, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cotoletta-di-vitello-servita-con-rucola-e-scaglie-di-parmigiano-31', 'Veal Cutlet with Arugula & Parmesan', 'COTOLETTA DI VITELLO SERVITA CON RUCOLA E SCAGLIE DI PARMIGIANO', 'Veal panè served with rocket and parmesan scales', 22, 'secondi_carne', 'https://cdn.casaitaliarestaurants.com/menu/Main dishes/COTOLETTA DI VITELLO.webp', NULL, NULL, '[]', NULL, NULL, 1, 31, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('fritto-di-mare-con-verdure-croccanti-32', 'Fried Seafood with Crispy Vegetables', 'FRITTO DI MARE CON VERDURE CROCCANTI', 'Fried seafood with crispy vegetables', 22, 'secondi_pesce', 'https://cdn.casaitaliarestaurants.com/menu/Main dishes/FRITTO DIMARECON.webp', NULL, NULL, '[]', NULL, NULL, 1, 32, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('filetto-di-salmone-con-salsa-ai-gamberi-servito-con-verdure-grigliate-33', 'Salmon Fillet with Shrimp Sauce', 'FILETTO DI SALMONE CON SALSA AI GAMBERI SERVITO CON VERDURE GRIGLIATE', 'Salmon fillet with shrimps sauce served with grilled vegetables', 24, 'secondi_pesce', 'https://cdn.casaitaliarestaurants.com/menu/Main dishes/FILETTO DI SALMONE CON SALSA AL GAMBERI.webp', NULL, NULL, '[]', NULL, NULL, 1, 33, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tagliata-di-tonno-in-crosta-di-pistacchio-su-crema-di-piselli-con-verdure-34', 'Pistachio-Crusted Tuna Steak on Pea Cream', 'TAGLIATA DI TONNO IN CROSTA DI PISTACCHIO SU CREMA DI PISELLI CON VERDURE', 'Sliced tuna in a pistachio crust on pea cream and vegetables', 26, 'secondi_pesce', 'https://cdn.casaitaliarestaurants.com/menu/Main dishes/TAGLIATA DI TONNO.webp', NULL, NULL, '[]', NULL, NULL, 1, 34, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('filetto-di-salmone-al-forno-su-crema-di-spinaci-con-patate-al-forno-35', 'Baked Salmon on Spinach Cream', 'FILETTO DI SALMONE AL FORNO SU CREMA DI SPINACI CON PATATE AL FORNO', 'Baked salmon fillet on creme of spinach with baked potatoes', 22, 'secondi_pesce', 'https://cdn.casaitaliarestaurants.com/menu/Main dishes/FILETTO DI SALMONE AL FORNO.webp', NULL, NULL, '[]', NULL, NULL, 1, 35, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('gamberi-grigliati-con-verdure-grigliate-36', 'Grilled Shrimp with Grilled Vegetables', 'GAMBERI GRIGLIATI CON VERDURE GRIGLIATE', 'Grilled shrimps with grilled vegetables', 26, 'secondi_pesce', 'https://cdn.casaitaliarestaurants.com/menu/Main dishes/GAMBERI GRIGLIATI.webp', NULL, NULL, '[]', NULL, NULL, 1, 36, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('spigola-all-arancia-con-patate-al-forno-37', 'Sea Bass with Orange & Roast Potatoes', 'SPIGOLA ALL''ARANCIA CON PATATE AL FORNO', 'Seabass with orange sauce served with baked potatoes', 22, 'secondi_pesce', '', NULL, NULL, '[]', NULL, NULL, 1, 37, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('verdure-grigliate-38', 'Grilled Vegetables', 'VERDURE GRIGLIATE', 'Grilled vegetables', 5, 'contorni', '', NULL, NULL, '[]', NULL, NULL, 1, 38, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('verdure-saltate-39', 'Sautéed Vegetables', 'VERDURE SALTATE', 'Sauteed vegetables', 5, 'contorni', '', NULL, NULL, '[]', NULL, NULL, 1, 39, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('insalata-40', 'Mixed Green Salad', 'INSALATA', 'Salad', 5, 'contorni', '', NULL, NULL, '[]', NULL, NULL, 1, 40, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('pur-41', 'Mashed Potatoes', 'PURÈ', 'Mashed potatoes', 5, 'contorni', '', NULL, NULL, '[]', NULL, NULL, 1, 41, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('patatine-fritte-42', 'French Fries', 'PATATINE FRITTE', 'French fries', 5, 'contorni', '', NULL, NULL, '[]', NULL, NULL, 1, 42, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('patate-al-forno-43', 'Roast Potatoes', 'PATATE AL FORNO', 'Baked potatoes', 5, 'contorni', '', NULL, NULL, '[]', NULL, NULL, 1, 43, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cheeseburger-44', 'Classic Cheeseburger', 'CHEESEBURGER', 'BIG Beef burger 200g, cheddar cheese, onion and pickled cucumbers served with fried potatoes', 13, 'burger', '', NULL, NULL, '[]', NULL, NULL, 1, 44, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('smashburger-45', 'Smash Burger', 'SMASHBURGER', 'BIG Beef burger 200g, salad, tomatoes and mustard served with fried potatoes', 17, 'burger', '', NULL, NULL, '[]', NULL, NULL, 1, 45, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('vegan-burger-46', 'Vegan Burger', 'VEGAN BURGER', 'Vegan burger, salad, fresh cucumber and onion', 13, 'burger', 'https://cdn.casaitaliarestaurants.com/menu/Burger/VEGAN BURGER.webp', NULL, NULL, '[]', NULL, NULL, 1, 46, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tuna-salad-48', 'Tuna Salad', 'TUNA SALAD', 'Tuna slices, tomatoes, salad, carrots and mozzarella', 12, 'insalate', 'https://cdn.casaitaliarestaurants.com/menu/Salad/TUNA SALAD.webp', NULL, NULL, '[]', NULL, NULL, 1, 47, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('caesar-49', 'Caesar Salad', 'CAESAR', 'Salad and parmesan', 12, 'insalate', 'https://cdn.casaitaliarestaurants.com/menu/Salad/CAESAR SALAD.webp', NULL, NULL, '[]', NULL, NULL, 1, 48, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('caprese-50', 'Caprese Salad', 'CAPRESE', 'Fresh tomato, mozzarella and basil sauce', 15, 'insalate', 'https://cdn.casaitaliarestaurants.com/menu/Salad/CAPRESE.webp', NULL, NULL, '[]', NULL, NULL, 1, 49, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('crudo-e-bufala-51', 'Prosciutto & Buffalo Mozzarella Salad', 'CRUDO E BUFALA', 'Raw ham and buffalo mozzarella', 19, 'insalate', 'https://cdn.casaitaliarestaurants.com/menu/Salad/CRUDO E BUFALA.webp', NULL, NULL, '[]', NULL, NULL, 1, 50, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('margherita-52', 'Margherita Pizza', 'MARGHERITA', 'Tomato sauce, mozzarella and basil', 9, 'pizze_rosse', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/RED/MARGHERITA.webp', NULL, NULL, '[]', NULL, NULL, 1, 51, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('marinara-53', 'Marinara Pizza', 'MARINARA', 'Tomato sauce, garlic and oregano', 7, 'pizze_rosse', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/RED/MARINARA.webp', NULL, NULL, '[]', NULL, NULL, 1, 52, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tonno-e-cipolla-54', 'Tuna & Onion Pizza', 'TONNO E CIPOLLA', 'Tomato sauce, mozzarella, tuna and onions', 10, 'pizze_rosse', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/RED/TONNO E CIPOLLA.webp', NULL, NULL, '[]', NULL, NULL, 1, 53, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('napoli-55', 'Napoli Pizza', 'NAPOLI', 'Tomato sauce, mozzarella, anchovies, capers', 10, 'pizze_rosse', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/RED/NAPOLI.webp', NULL, NULL, '[]', NULL, NULL, 1, 54, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('crudo-rucola-e-grana-56', 'Prosciutto, Arugula & Grana Pizza', 'CRUDO, RUCOLA E GRANA', 'Tomato sauce, mozzarella, raw ham, rocket and parmesan flakes', 16, 'pizze_rosse', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/RED/CRUDO RUCOLA E GRANA.webp', NULL, NULL, '[]', NULL, NULL, 1, 55, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('bufalina-57', 'Buffalo Mozzarella Pizza', 'BUFALINA', 'Tomato sauce, buffalo mozzarella and basil', 14, 'pizze_rosse', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/RED/BUFALINA.webp', NULL, NULL, '[]', NULL, NULL, 1, 56, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('vegetariana-58', 'Vegetarian Pizza', 'VEGETARIANA', 'Tomato sauce, mozzarella and grilled vegetables', 12, 'pizze_rosse', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/RED/VEGETARIANA.webp', NULL, NULL, '[]', NULL, NULL, 1, 57, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('frutti-di-mare-59', 'Seafood Pizza', 'FRUTTI DI MARE', 'Tomato sauce, mozzarella and seafood', 15, 'pizze_rosse', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/RED/FRUTTI DI MARE.webp', NULL, NULL, '[]', NULL, NULL, 1, 58, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('salamino-60', 'Salami Pizza', 'SALAMINO', 'Tomato sauce, mozzarella and salami (pork salami OR cow salami)', 16, 'pizze_rosse', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/RED/SALAMINO.webp', NULL, NULL, '[]', NULL, NULL, 1, 59, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('calzone-port-ghalib-61', 'Port Ghalib Calzone', 'CALZONE PORT GHALIB', 'Tomato sauce, mozzarella, cooked ham', 12, 'pizze_rosse', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/RED/CALZONE.webp', NULL, NULL, '[]', NULL, NULL, 1, 60, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('gamberi-e-zucchine-62', 'Shrimp & Zucchini Pizza', 'GAMBERI E ZUCCHINE', 'Mozzarella, shrimps and zucchinis', 14, 'pizze_bianche', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/WHITE/GAMBERI E ZUCCHINE.webp', NULL, NULL, '[]', NULL, NULL, 1, 61, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('mortadella-burrata-e-pistacchi-63', 'Mortadella, Burrata & Pistachio Pizza', 'MORTADELLA, BURRATA E PISTACCHI', 'Mozzarella, mortadella, burrata and pistachios', 18, 'pizze_bianche', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/WHITE/MORTADELLA BURRATA E PISTACCHI.webp', NULL, NULL, '[]', NULL, NULL, 1, 62, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('quattro-formaggi-64', 'Four Cheese Pizza', 'QUATTRO FORMAGGI', 'Four cheeses', 12, 'pizze_bianche', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/WHITE/QUATTRO FORMAGGI.webp', NULL, NULL, '[]', NULL, NULL, 1, 63, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('pane-arabo-salmone-avocado-e-formaggio-65', 'Arabic Bread with Salmon, Avocado & Cheese', 'PANE ARABO SALMONE, AVOCADO E FORMAGGIO', 'Salmon, avocado and cheese', 16, 'pizze_bianche', '', NULL, NULL, '[]', NULL, NULL, 1, 64, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('speck-mascarpone-e-noci-66', 'Speck, Mascarpone & Walnut Pizza', 'SPECK, MASCARPONE E NOCI', 'Speck, cheese and walnuts', 18, 'pizze_bianche', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/WHITE/SPECK MASCARPONE E NOCI.webp', NULL, NULL, '[]', NULL, NULL, 1, 65, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tartufo-67', 'Truffle Pizza', 'TARTUFO', 'Mozzarella, truffle cream and truffle oil', 18, 'pizze_bianche', 'https://cdn.casaitaliarestaurants.com/menu/Pizza/WHITE/TARTUFO.webp', NULL, NULL, '[]', NULL, NULL, 1, 66, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tiramis-68', 'Traditional Tiramisù', 'TIRAMISÙ', 'Traditional Tiramisù', 7, 'dolci', '', NULL, NULL, '[]', NULL, NULL, 1, 67, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('tortino-al-cioccolato-con-panna-69', 'Chocolate Lava Cake with Cream', 'TORTINO AL CIOCCOLATO CON PANNA', 'Chocolate cake with whipped cream', 6, 'dolci', '', NULL, NULL, '[]', NULL, NULL, 1, 68, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('sgroppino-70', 'Sgroppino Lemon Sorbet Cocktail', 'SGROPPINO', 'Lemon ice cream, vodka and prosecco', 7, 'dolci', '', NULL, NULL, '[]', NULL, NULL, 1, 69, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('gnocco-fritto-71', 'Fried Dough Puffs', 'GNOCCO FRITTO', 'Fried dumpling with chocolate, pistachio or white chocolate', 5, 'dolci', '', NULL, NULL, '[]', NULL, NULL, 1, 70, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('coppa-gelato-72', 'Gelato Cup', 'COPPA GELATO', 'Ice cream cup: lemon, strawberry, mango, chocolate or vanilla', 6, 'dolci', '', NULL, NULL, '[]', NULL, NULL, 1, 71, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cheesecake-73', 'Cheesecake', 'CHEESECAKE', 'Cheesecake', 6, 'dolci', '', NULL, NULL, '[]', NULL, NULL, 1, 72, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('torta-del-giorno-74', 'Cake of the Day', 'TORTA DEL GIORNO', 'Cake of the day', 5, 'dolci', '', NULL, NULL, '[]', NULL, NULL, 1, 73, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('caff-espresso-75', 'Espresso', 'CAFFÈ ESPRESSO', '', 2.5, 'caffetteria', '', NULL, NULL, '[]', NULL, NULL, 1, 74, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('caff-macchiato-76', 'Macchiato', 'CAFFÈ MACCHIATO', '', 3, 'caffetteria', '', NULL, NULL, '[]', NULL, NULL, 1, 75, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cappuccino-77', 'Cappuccino', 'CAPPUCCINO', '', 3.5, 'caffetteria', '', NULL, NULL, '[]', NULL, NULL, 1, 76, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('latte-bianco-78', 'Steamed Milk', 'LATTE BIANCO', 'White milk', 2, 'caffetteria', '', NULL, NULL, '[]', NULL, NULL, 1, 77, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('latte-macchiato-79', 'Latte Macchiato', 'LATTE MACCHIATO', 'Flat white', 3, 'caffetteria', '', NULL, NULL, '[]', NULL, NULL, 1, 78, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('caff-americano-80', 'Americano', 'CAFFÈ AMERICANO', '', 2.5, 'caffetteria', '', NULL, NULL, '[]', NULL, NULL, 1, 79, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('macha-latte-81', 'Matcha Latte', 'MACHA LATTE', '', 4, 'caffetteria', '', NULL, NULL, '[]', NULL, NULL, 1, 80, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('caff-freddo-82', 'Iced Coffee', 'CAFFÈ FREDDO', 'Ice coffee', 3.5, 'caffetteria', '', NULL, NULL, '[]', NULL, NULL, 1, 81, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('acqua-1l-still-83', 'Still Water 1L', 'ACQUA 1L STILL', 'Still water 1L', 3.5, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 82, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('acqua-0-5l-sparkling-84', 'Sparkling Water 0.5L', 'ACQUA 0.5L SPARKLING', 'Sparkling water 0.5L', 2.5, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 83, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('schweppes-soda-85', 'Schweppes Soda', 'SCHWEPPES SODA', '', 2.5, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 84, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('schweppes-tonic-86', 'Schweppes Tonic', 'SCHWEPPES TONIC', '', 2.5, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 85, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('sprite-87', 'Sprite', 'SPRITE', '', 2.5, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 86, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('fanta-88', 'Fanta', 'FANTA', '', 2.5, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 87, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('coca-cola-89', 'Coca Cola', 'COCA COLA', '', 2.5, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 88, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('coca-cola-zero-90', 'Coca Cola Zero', 'COCA COLA ZERO', '', 2.5, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 89, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('the-sant-anna-91', 'Sant''Anna Iced Tea', 'THE SANT''ANNA', '', 2.5, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 90, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('red-bull-92', 'Red Bull', 'RED BULL', '', 4, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 91, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('spremuta-fresh-juice-93', 'Fresh Squeezed Juice', 'SPREMUTA FRESH JUICE', 'Lemon, Orange, or Mango', 5, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 92, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('fever-tree-ginger-ale-94', 'Fever Tree Ginger Ale', 'FEVER-TREE GINGER ALE', '', 3, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 93, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('fever-tree-soda-mexican-lime-95', 'Fever Tree Mexican Lime Soda', 'FEVER-TREE SODA MEXICAN LIME', '', 3, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 94, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('fever-tree-soda-pink-grapefruit-96', 'Fever Tree Pink Grapefruit Soda', 'FEVER-TREE SODA PINK GRAPEFRUIT', '', 3, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 95, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('fever-tree-tonic-water-97', 'Fever Tree Tonic Water', 'FEVER-TREE TONIC WATER', '', 3, 'bibite', '', NULL, NULL, '[]', NULL, NULL, 1, 96, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('capebay-white-98', 'Capebay White Wine', 'CAPEBAY WHITE', 'Chardonnay (Glass: €6)', 30, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 97, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('castello-di-trevi-white-99', 'Castello di Trevi White Wine', 'CASTELLO DI TREVI WHITE', 'Vermentino (Glass: €7)', 35, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 98, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('chateau-de-granville-white-100', 'Chateau de Granville White Wine', 'CHATEAU DE GRANVILLE WHITE', 'Semillon (Glass: €8)', 40, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 99, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('jardin-du-nil-white-101', 'Jardin du Nil White Wine', 'JARDIN DU NIL WHITE', 'Vermentino (Glass: €7)', 35, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 100, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('grand-marquis-white-102', 'Grand Marquis White Wine', 'GRAND MARQUIS WHITE', 'Sultanine Blanche (Glass: €8)', 40, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 101, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('chateau-byblos-white-103', 'Chateau Byblos White Wine', 'CHATEAU BYBLOS WHITE', 'Chardonnay, Sauvignon (Glass: €7)', 35, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 102, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('capebay-red-104', 'Capebay Red Wine', 'CAPEBAY RED', 'Merlot (Glass: €6)', 30, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 103, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('castello-di-trevi-red-105', 'Castello di Trevi Red Wine', 'CASTELLO DI TREVI RED', 'Merlot, Syrah (Glass: €7)', 35, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 104, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('chateau-de-granville-red-106', 'Chateau de Granville Red Wine', 'CHATEAU DE GRANVILLE RED', 'Cabernet, Sauvignon (Glass: €8)', 40, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 105, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('grand-marquis-red-107', 'Grand Marquis Red Wine', 'GRAND MARQUIS RED', 'Carignan, Syrah (Glass: €8)', 40, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 106, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('jardin-du-nil-red-108', 'Jardin du Nil Red Wine', 'JARDIN DU NIL RED', 'Cabernet, Sauvignon, Syrah (Glass: €7)', 35, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 107, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('castello-di-trevi-ros-109', 'Castello di Trevi Rosé Wine', 'CASTELLO DI TREVI ROSÉ', 'Rosé (Glass: €8)', 40, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 108, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('le-baron-ros-110', 'Le Baron Rosé Wine', 'LE BARON ROSÉ', 'Sparkling Rosé', 45, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 109, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('le-baron-white-111', 'Le Baron White Wine', 'LE BARON WHITE', 'Sparkling White', 45, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 110, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('valmont-ros-112', 'Valmont Rosé Wine', 'VALMONT ROSÉ', 'Sparkling Rosé (Glass: €7)', 35, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 111, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('valmont-white-113', 'Valmont White Wine', 'VALMONT WHITE', 'Sparkling White (Glass: €7)', 35, 'vini', '', NULL, NULL, '[]', NULL, NULL, 1, 112, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('heineken-114', 'Heineken Beer', 'HEINEKEN', '', 5, 'birre', '', NULL, NULL, '[]', NULL, NULL, 1, 113, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('stella-115', 'Stella Artois Beer', 'STELLA', '', 5, 'birre', '', NULL, NULL, '[]', NULL, NULL, 1, 114, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('sakara-116', 'Sakara Beer', 'SAKARA', '', 5, 'birre', '', NULL, NULL, '[]', NULL, NULL, 1, 115, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('meister-max-117', 'Meister Max Beer', 'MEISTER MAX', '', 5, 'birre', '', NULL, NULL, '[]', NULL, NULL, 1, 116, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('desperados-118', 'Desperados Beer', 'DESPERADOS', '', 5, 'birre', '', NULL, NULL, '[]', NULL, NULL, 1, 117, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cosmopolitan-119', 'Cosmopolitan', 'COSMOPOLITAN', 'Vodka, triple sec, sour mix, cranberry juice', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 118, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('espresso-martini-120', 'Espresso Martini', 'ESPRESSO MARTINI', 'Vodka, espresso, kahlua liquor', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 119, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('martini-121', 'Martini Cocktail', 'MARTINI', 'Gin, dry vermouth, sour mix (choose flavour)', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 120, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('margarita-122', 'Margarita', 'MARGARITA', 'Tequila, cointreau, sour mix (choose flavour)', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 121, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('daiquiri-123', 'Daiquiri', 'DAIQUIRI', 'Rum, triple sec, sour mix (choose flavour)', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 122, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('mojito-124', 'Mojito', 'MOJITO', 'Light rum, lime wedge, fresh mint, soda', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 123, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('pina-colada-125', 'Piña Colada', 'PINA COLADA', 'Light rum, coconut milk, pineapple juice', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 124, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('mai-tai-126', 'Mai Tai', 'MAI TAI', 'Light rum, almond, triple sec, sour mix, dark rum', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 125, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('moscow-mule-127', 'Moscow Mule', 'MOSCOW MULE', 'Vodka, ginger beer, lime juice', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 126, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('whisky-sour-128', 'Whisky Sour', 'WHISKY SOUR', 'Whisky, sour mix, egg white', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 127, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('caipirinha-129', 'Caipirinha', 'CAIPIRINHA', 'Rum, sour mix, lime wedge', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 128, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('glue-wine-130', 'Mulled Wine', 'GLUE WINE', 'Hot red wine, fresh orange, fresh lemon, sugar syrup, anise and cinnamon stick', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 129, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('long-island-131', 'Long Island Iced Tea', 'LONG ISLAND', 'Vodka, rum, gin, triple sec, sour mix, cola', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 130, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('bull-frog-132', 'Bull Frog Cocktail', 'BULL FROG', 'Vodka, rum, gin, tequila, blue curacao, redbull', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 131, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('sex-on-the-beach-133', 'Sex on the Beach', 'SEX ON THE BEACH', 'Vodka, peach schnapps, orange, cranberry', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 132, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('fruit-smoothie-134', 'Fruit Smoothie', 'FRUIT SMOOTHIE', 'Avocado, cucumber, banana', 7, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 133, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('passion-fruit-smoothie-135', 'Passion Fruit Smoothie', 'PASSION FRUIT SMOOTHIE', 'Passion puree, vanilla ice cream, milk', 7, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 134, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('virgin-blue-hawaii-136', 'Virgin Blue Hawaii', 'VIRGIN BLUE HAWAII', 'Coconut milk, blue curacao, almond, pineapple', 7, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 135, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('miami-voice-137', 'Miami Voice Mocktail', 'MIAMI VOICE', 'Strawberry, banana, coconut milk', 7, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 136, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('melon-ball-138', 'Melon Ball Cocktail', 'MELON BALL', 'Melon, pineapple rings, redbull', 7, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 137, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('kiwi-kama-139', 'Kiwi Kama Cocktail', 'KIWI KAMA', 'Kiwi, banana, pineapple, coconut milk', 7, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 138, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('virgin-mojito-140', 'Virgin Mojito', 'VIRGIN MOJITO', 'Lime wedge, fresh mint, sprite, brown sugar', 7, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 139, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('virgin-pina-colada-141', 'Virgin Piña Colada', 'VIRGIN PINA COLADA', 'Coconut milk, pineapple juice', 7, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 140, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('blueberry-fruit-boba-142', 'Blueberry Fruit Boba', 'BLUEBERRY FRUIT BOBA', 'Blueberry puree, vanilla ice cream, milk, boba', 7, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 141, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('passion-fruit-boba-143', 'Passion Fruit Boba', 'PASSION FRUIT BOBA', 'Passion puree, vanilla ice cream, pineapple juice, boba', 7, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 142, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('orange-spritz-144', 'Orange Spritz', 'ORANGE SPRITZ', 'Aperitif cocktail', 12, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 143, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('red-spritz-145', 'Red Spritz', 'RED SPRITZ', 'Aperitif cocktail', 12, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 144, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('lemon-spritz-146', 'Lemon Spritz', 'LEMON SPRITZ', 'Aperitif cocktail', 12, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 145, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('hugo-spritz-147', 'Hugo Spritz', 'HUGO SPRITZ', 'Elderflower, prosecco and soda', 12, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 146, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('bellini-148', 'Bellini', 'BELLINI', 'Peach, prosecco', 12, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 147, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('rossini-149', 'Rossini', 'ROSSINI', 'Strawberry, prosecco', 12, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 148, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('negroni-150', 'Negroni', 'NEGRONI', 'Classic Negroni cocktail', 12, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 149, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('pear-whisper-151', 'Pear Whisper Mocktail', 'PEAR WHISPER', 'Vodka, pear puree, rosemary syrup, soda', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 150, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('bamboska-152', 'Bamboska Cocktail', 'BAMBOSKA', 'Vodka, cardamom, coconut milk, mango juice', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 151, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('spa-cucumber-153', 'Spa Cucumber Mocktail', 'SPA CUCUMBER', 'Rum, fresh cucumber, watermelon, honey, redbull', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 152, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('kink-tout-154', 'Kink Tout Cocktail', 'KINK TOUT', 'Gin, hibiscus, lime, cranberry', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 153, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('matcha-lift-155', 'Matcha Lift Mocktail', 'MATCHA LIFT', 'Dark rum, matcha, banana, vanilla, soda', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 154, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('bob-marley-156', 'Bob Marley Mocktail', 'BOB MARLEY', 'Vodka, pineapple juice, grenadine, blue curacao', 10, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 155, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('dodo-157', 'Dodo Cocktail', 'DODO', 'Vodka, lemon, tabasco, olive', 5, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 156, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('black-russian-158', 'Black Russian', 'BLACK RUSSIAN', 'Vodka, kahlua', 5, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 157, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('snake-bite-159', 'Snake Bite Cocktail', 'SNAKE BITE', 'Tequila, sour mix', 5, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 158, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('green-tea-shoot-160', 'Green Tea Shot', 'GREEN TEA SHOOT', 'Irish whisky, peach schnapps, sour mix', 5, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 159, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('sambuca-161', 'Sambuca Digestif', 'SAMBUCA', 'Shot', 5, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 160, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('grappa-162', 'Grappa Digestif', 'GRAPPA', 'Shot', 5, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 161, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('limoncello-163', 'Limoncello Digestif', 'LIMONCELLO', 'Shot', 5, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 162, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('amaro-164', 'Amaro Digestif', 'AMARO', 'Shot', 5, 'cocktails', '', NULL, NULL, '[]', NULL, NULL, 1, 163, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cornetto-vuoto-165', 'Plain Croissant', 'CORNETTO VUOTO', 'Plain croissant', 2, 'colazione', '', NULL, NULL, '[]', NULL, NULL, 1, 164, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cornetto-ripieno-166', 'Filled Croissant', 'CORNETTO RIPIENO', 'Filled croissant with chocolate, white chocolate, pistachio cream, or jam', 2.5, 'colazione', '', NULL, NULL, '[]', NULL, NULL, 1, 165, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cornetto-con-gelato-167', 'Croissant with Gelato', 'CORNETTO CON GELATO', 'Ice-cream croissant', 4, 'colazione', '', NULL, NULL, '[]', NULL, NULL, 1, 166, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('muffin-gluten-free-168', 'Gluten Free Muffin', 'MUFFIN GLUTEN FREE', 'Gluten-free muffin', 2.5, 'colazione', '', NULL, NULL, '[]', NULL, NULL, 1, 167, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('pan-au-chocolat-169', 'Pain au Chocolat', 'PAN AU CHOCOLAT', 'Saccottino', 2.5, 'colazione', '', NULL, NULL, '[]', NULL, NULL, 1, 168, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('torta-del-giorno-170', 'Cake of the Day', 'TORTA DEL GIORNO', 'Cake of the day', 5, 'colazione', '', NULL, NULL, '[]', NULL, NULL, 1, 169, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cornetto-salato-pomodoro-e-mozzarella-171', 'Savory Croissant - Tomato & Mozzarella', 'CORNETTO SALATO - POMODORO E MOZZARELLA', 'Savory croissant with tomato and mozzarella', 5, 'colazione', '', NULL, NULL, '[]', NULL, NULL, 1, 170, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cornetto-salato-salmone-avocado-e-formaggio-172', 'Savory Croissant - Salmon, Avocado & Cheese', 'CORNETTO SALATO - SALMONE, AVOCADO E FORMAGGIO', 'Savory croissant with salmon, avocado and cheese', 7, 'colazione', '', NULL, NULL, '[]', NULL, NULL, 1, 171, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('cornetto-salato-tonno-pomodoro-e-maionese-173', 'Savory Croissant - Tuna, Tomato & Mayo', 'CORNETTO SALATO - TONNO, POMODORO E MAIONESE', 'Savory croissant with tuna, tomato and mayo', 5, 'colazione', '', NULL, NULL, '[]', NULL, NULL, 1, 172, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
INSERT OR REPLACE INTO menu_items (id, name, italian_name, description, price, category, image, calories, preparation_time, tags, badge, pronunciation, active, display_order, created_at, updated_at) VALUES ('omelette-174', 'Omelette', 'OMELETTE', 'Breakfast Omelette', 9, 'colazione', '', NULL, NULL, '[]', NULL, NULL, 1, 173, '2026-09-19T19:35:02.714Z', '2026-09-19T19:35:02.714Z');
